---
- name: Download Conf
  become: true
  hosts: S3
  gather_facts: no
  tasks:

#task 1: docker version
    - name: Version
      shell: |
        curl http://localhost:5012/systemState | python3 -m json.tool | grep system_version | cut -d':' -f2 | cut -d '"' -f2
      register: system_version
      
#task 2: Ship name
    - name: Ship name
      shell: |
        sudo docker exec consul consul kv get -recurse shared/HOST_NAME | cut -d':' -f2 | grep -oe '[a-Z-]*'
      register: ship_name
    - debug:
        var: ship_name.stdout 
      
#task 2.1: Download Conf
    - name: Download Conf
      shell: |
        sudo docker run -v ~/.docker/config.json:/root/.docker/config.json -v /var/run/docker.sock:/var/run/docker.sock -v /orcaai/orcaai-storage:/orcaai/orcaai-storage --network host --privileged registry.gitlab.com/orca_ai/orcaai-ship/ship-cli:{{ system_version.stdout }} make set-cloud-configs ship={{ ship_name.stdout }} version={{ system_version.stdout }}
      register: Download_Conf
    - debug:
        var: Download_Conf.stdout 

#task 2.1: restart dockers
    - name: restart dockers
      shell: |
        sudo docker run -v ~/.docker/config.json:/root/.docker/config.json -v /var/run/docker.sock:/var/run/docker.sock -v /orcaai/orcaai-storage:/orcaai/orcaai-storage --network host --privileged registry.gitlab.com/orca_ai/orcaai-ship/ship-cli:{{ system_version.stdout }} make restart-all
      register: Restart_Dockers
    - debug:
        var: Restart_Dockers.stdout 
