---
- name: Check SOG status
  hosts: ships
  become: true
  gather_facts: no
  tasks:

#task 1: to check the storage
    - name: Check SOG status.
      shell: |
        curl -s http://localhost:5010/pvt | grep sog | cut -d':' -f11 | cut -d"," -f1
      register: Sog_status
    - debug: msg="The sog of the ship is {{ Sog_status.stdout }}"
    
    
#task 5: email to the slack
    - name: Email operation results
      mail:
        host: smtp.gmail.com
        port: 587
        username: techops@orca-ai.io
        password: kianjnebnygzopob
        to: ansible-draft-aaaahachuioeorzkha5frffoha@orcaai.slack.com
        subject: Ansible-Sog-Check
        body: System {{ inventory_hostname }} are on {{ Sog_status.stdout }} SOG
      when: Sog_status.stdout | float <= 1.0
      delegate_to: localhost

      
