---
- name: Copy file to remote host
  hosts: test-bit
  become: true
  gather_facts: false

  tasks:
    - name: Verify directory existence
      stat:
        path: "/orcaai/orcaai-storage/site/assets/i18n"
      register: dir_check

    - name: Create directory if it doesn't exist
      file:
        path: "/orcaai/orcaai-storage/site/assets/i18n"
        state: directory
      when: not dir_check.stat.exists

    - name: Verify file existence
      stat:
        path: "/orcaai/orcaai-storage/site/assets/i18n/en.json"
      register: file_check

    - name: Copy file to remote host
      copy:
        src: "/home/orca-ghost/Desktop/do_not_touch/en.json"
        dest: "/orcaai/orcaai-storage/site/assets/i18n/en.json"
      when: not file_check.stat.exists or file_check.stat.islnk

    - name: Update file permissions
      file:
        path: "/orcaai/orcaai-storage/site/assets/i18n/en.json"
        mode: 0644

